/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Source;


import Source.model.Subject;
import Source.model.attendance;
import Source.model.database;
import Source.model.kelas;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wa Ode Raksni Dumpatua
 */
public class addAttendanceFormin extends javax.swing.JInternalFrame {

    /**
     * Creates new form addTeacherFormin
     */

    public addAttendanceFormin() {
        initComponents();
        tampil_subject();
        loadTableData();
        session.setSelectedIndex(-1);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        date.setText(sdf.format(new Date()));
        date.setEditable(false);
    }
    
    
    
    public final void tampil_subject(){
        try {
            ArrayList<String> subjects = (ArrayList<String>) database.getInstance().getListSubject();
            int n = subjects.size();
            for (int i = 0; i < n; i++) {
                subject.addItem(subjects.get(i));
            }
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    
    }
    
    private void clearForm(){
        subject.setSelectedIndex(0);
        kelas.setSelectedIndex(-1);
        session.setSelectedIndex(-1);
              
    }
    
    private void loadTableData(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        //refresh tabel
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        try{
        //isi tabel 
            for(attendance sub:
            database.getInstance().getAttendanceBatch()){
                dtm.addRow(new Object[]{sub.getDate(),sub.getKelas().getClassname(),sub.getSubject().getSubjectname(),sub.getSession()});
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data table", "Gagal", JOptionPane.ERROR_MESSAGE);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kelas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        session = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setTitle("Attendence Batch Management");
        setMaximumSize(new java.awt.Dimension(990, 550));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(790, 614));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 90, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Attendance Batch Form");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 40, 220, 22);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Session");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 240, 150, 30);

        kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Kelas---"}));
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        getContentPane().add(kelas);
        kelas.setBounds(380, 190, 180, 30);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Subject");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 140, 150, 30);

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Mata Kuliah---"}));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        getContentPane().add(subject);
        subject.setBounds(380, 140, 180, 30);

        add.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(530, 300, 75, 30);

        session.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Session 1", "Session 2", "Session 3", "Session 4" }));
        getContentPane().add(session);
        session.setBounds(380, 240, 180, 30);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Class");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 190, 150, 30);

        clear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(650, 300, 90, 30);
        getContentPane().add(date);
        date.setBounds(380, 90, 180, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Class", "Subject", "Session"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(42, 340, 710, 210);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/res/black1.jpg"))); // NOI18N
        jLabel2.setText("Lec");
        jLabel2.setPreferredSize(new java.awt.Dimension(794, 565));
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 570);
        setBounds(0, 0, 790, 570);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 6, 810, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_kelasActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
        //String[] bagian = kodeProvComboBox.getSelectedItem().toString().split("-");
        
        try {
            kelas.removeAllItems();
            String subjectid = database.getInstance().getSubjectId(subject.getSelectedItem().toString());
            ArrayList<String> k = (ArrayList<String>) database.getInstance().getListSubjectClass(subjectid);
            int n = k.size();
            for (int i = 0; i < n; i++) {
                kelas.addItem(k.get(i));
            }
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_subjectActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        attendance att = new attendance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        att.setDate(sdf.format(new Date()));
        att.setSession(session.getSelectedItem().toString());
        kelas kls = new kelas();
        kls.setClassname(kelas.getSelectedItem().toString());
        att.setKelas(kls);
        Subject sub = new Subject();
        sub.setSubjectname(subject.getSelectedItem().toString());
        try{
            sub.setSubjectid(database.getInstance().getSubjectId(sub.getSubjectname()));
            att.setSubject(sub);
            database.getInstance().insertAttendance(att);
            JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
        }catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Gagal menambah data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
        loadTableData();
        clearForm();
        subject.setEditable(true);
        kelas.setEditable(true);
        
    }//GEN-LAST:event_addActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        kelas.removeAllItems();
        subject.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
        kelas.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
        
        subject.setEditable(false);
        kelas.setEditable(false);
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> kelas;
    private javax.swing.JComboBox<String> session;
    private javax.swing.JComboBox<String> subject;
    // End of variables declaration//GEN-END:variables
}
