/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Source;


import Source.model.Mahasiswa;
import Source.model.database;
import Source.model.kelas;
import Source.model.teacher;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wa Ode Raksni Dumpat
 */
public class addStudentFormin extends javax.swing.JInternalFrame {

    /**
     * Creates new form addTeacherFormin
     */
    public addStudentFormin() {
        initComponents();
        tampil_subject();
        loadTableData();
    }
    
    public final void tampil_subject(){
        try {
            ArrayList<String> subjects = (ArrayList<String>) database.getInstance().getListClass();
            int n = subjects.size();
            for (int i = 0; i < n; i++) {
                kelas.addItem(subjects.get(i));
            }
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    
    }
    
    private void clearForm(){
        id.setText("");
        name.setText("");
        semester.setText("");
        kelas.setSelectedIndex(-1);
        dept.setSelectedIndex(-1);
        id.setEditable(true);
    }
    
    private void loadTableData(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        //refresh tabel
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        try{
        //isi tabel 
            for(Mahasiswa sub:
            database.getInstance().getListMahasiswa()){
                dtm.addRow(new Object[]{sub.getNim(),sub.getNama(),sub.getKelas(),sub.getDept(),sub.getSemester()});
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data table", "Gagal", JOptionPane.ERROR_MESSAGE);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kelas = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        dept = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Student Data Management");
        setMaximumSize(new java.awt.Dimension(990, 550));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(790, 614));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 100, 150, 30);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 150, 150, 30);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departement");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 100, 150, 30);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semester");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 150, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add Student Form");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 40, 220, 22);

        id.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(200, 100, 150, 30);

        name.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(name);
        name.setBounds(200, 150, 150, 30);

        semester.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });
        getContentPane().add(semester);
        semester.setBounds(580, 150, 150, 30);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Class");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 200, 150, 30);

        kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        getContentPane().add(kelas);
        kelas.setBounds(200, 200, 150, 30);

        add.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(360, 270, 75, 30);

        clear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(60, 270, 90, 30);

        update.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(490, 270, 110, 30);

        delete.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(650, 270, 90, 30);

        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih Departemen---","D4 Komputasi", "D4 Statistika", "D3 Statistika"}));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });
        getContentPane().add(dept);
        dept.setBounds(580, 100, 150, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Class", "Departement", "Semester"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(42, 320, 710, 230);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/res/black1.jpg"))); // NOI18N
        jLabel2.setText("Lec");
        jLabel2.setPreferredSize(new java.awt.Dimension(794, 565));
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 570);
        setBounds(0, 0, 790, 570);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 6, 790, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
                
    }//GEN-LAST:event_kelasActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhs = new Mahasiswa();
        mhs.setNim(id.getText());
        mhs.setNama(name.getText());
        kelas kls = new kelas();
        kls.setClassname(kelas.getSelectedItem().toString());
        mhs.setKelas(kls);
        mhs.setSemester(semester.getText());
       
        mhs.setDept(dept.getSelectedItem().toString());
        try{
            database.getInstance().insertMahasiswa(mhs);
            JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
        }catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Gagal menambah data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
        clearForm();
        loadTableData();
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhs = new Mahasiswa();
        mhs.setNim(id.getText());
        mhs.setNama(name.getText());
        kelas kls = new kelas();
        kls.setClassname(kelas.getSelectedItem().toString());
        mhs.setKelas(kls);
        mhs.setSemester(semester.getText());       
        mhs.setDept(dept.getSelectedItem().toString());
        try{    
            database.getInstance().updateStudent(mhs);
            JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
            
        }catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Gagal menambah data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
        loadTableData();
        clearForm();
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        id.setText(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
        name.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
        kelas.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
        dept.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
        semester.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
        
        id.setEditable(false);
        name.setEditable(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhs = new Mahasiswa();
        mhs.setNim(id.getText());
        int op = JOptionPane.showConfirmDialog(null,"Do you really want to logout?","confirm",0);
        //System.out.println(""+op);
        if(op == 0)
        {
                try{
                    database.getInstance().deleteStudent(mhs);
                    JOptionPane.showMessageDialog(this, "Sukses TerHapus");
                }catch(SQLException e){
                    System.out.println(e);
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data", "Gagal", JOptionPane.ERROR_MESSAGE);
                }
                loadTableData();
                clearForm();
        }
        else{
           // dispose();
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> kelas;
    private javax.swing.JTextField name;
    private javax.swing.JTextField semester;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
